stages:
  # - test
  - build
  - release

# test:
#   stage: test
#   image: docker.viriciti.com/building-tools/project-compiler
#   services:
#     - toke/mosquitto
#   script:
#     - npm install --production
#     - ln -s /usr/local/lib/node_modules/tape node_modules/tape
#     - npm test
#   only:
#     - tags

build:
  stage: build
  image: docker.viriciti.com/building-tools/project-compiler
  artifacts:
    paths:
      - build
  script:
    - npm run build
  only:
    - tags

release:
  stage: release
  image: docker.viriciti.com/vems/nodejs-project-base
  script:
    - npm publish
  only:
    - tags
